### ISSUE TITLE
Can't use a state processor with DELETE operation

### ISSUE THREAD

**Issue by eddyger** [api-platform/api-platform#2539]
**API Platform version(s) affected**: 3.1.2

**Description**  
In the [documentation](https://api-platform.com/docs/core/state-processors/), it is said that we can use state processor with DELETE operation. But when I try to do so I have got a message like this one :

> "@context": "/api/contexts/Error",
>     "@type": "hydra:Error",
>     "hydra:title": "An error occurred",
>     "hydra:description": "Could not resolve argument $data of \"api_platform.action.placeholder::__invoke()\", maybe you forgot to register the controller as a service or missed tagging it with the \"controller.service_arguments\"?",

**How to reproduce**  
Below my code
```
#[Delete(
    uriTemplate: '/my-url/var1/{var1}/var2/{var2}/do-delete',
    read: false,
    processor: MyCustomProcessor::class
)]
class MyCustomResource
{
}

class MyCustomProcessor implements ProcessorInterface
{
    public function process(mixed $data, Operation $operation, array $uriVariables = [], array $context = [])
    {
        dd($data);
    }
}
```

**Possible Solution**  
I noticed that when 'data' attribute is set (eg. request->attributes->set('data',null)), it works (my state processor is called)

**Comment by luzrain** [comment]
Same here.

**Comment by luzrain** [comment]
Temporary solution.
```php
use ApiPlatform\Metadata\Delete;
use ApiPlatform\Metadata\Operation;
use Symfony\Component\EventDispatcher\Attribute\AsEventListener;
use Symfony\Component\HttpKernel\Event\RequestEvent;

#[AsEventListener(event: RequestEvent::class)]
final class DeleteCustomProcessorFix
{
    public function __invoke(RequestEvent $event): void
    {
        /** @var Operation|null $operation */
        $operation = $event->getRequest()->attributes->get('_api_operation');
        $processor = $operation?->getProcessor();

        if ($operation instanceof Delete && $processor !== null) {
            $event->getRequest()->attributes->set('data', null);
        }
    }
}
```

**Comment by soyuka** [comment]
hi fixed in 3.2 use `write: true`

**Comment by senaria** [comment]
hi @soyuka I apparently also ran into this issue here.

Setting `write: true` on the operation seem to have no effect. I though can get it working with [this](https://github.com/api-platform/api-platform/issues/2539#issuecomment-1790341634) solution. 

Could you give an example how the `write: true` solution should look like? Currently I try it with 

```
        new Delete(
            uriTemplate: '/dynamic-assets/login-logo',
            security: 'is_granted("ROLE_ADMIN")',
            write: true,
            processor: DynamicAssetProcessor::class
        ),
```

**Comment by soyuka** [comment]
if you're using event listeners backward compatibility it doesn't work

**Comment by finnef** [comment]
I have the same issue when doing a POST request to upload a file, using the example from the [docs](https://api-platform.com/docs/core/file-upload/)
Not sure how to use a StateProvider, and write: true does not work for me on API Platform 3.3.2. 
The EventListener solution to insert the data attribute does work for me.

**Comment by AliKHODR** [comment]
@senaria @soyuka i added `write: true` but it still doesn't work ! i'm on api-platform 3.2.14.

**Comment by soyuka** [comment]
```php
<?php

namespace ApiPlatform\Tests\Fixtures\TestBundle\ApiResource\Issue2539;

use ApiPlatform\Metadata\Delete;
use ApiPlatform\Metadata\Operation;

#[Delete(
    read: false,
    uriTemplate: '/delete/{id}/with/{b}', uriVariables: ['id', 'b'], processor: [self::class, 'process']
)]
class DeleteWithProcessor
{
    public string $id;
    public string $b;

    public static function process(mixed $data, Operation $operation, array $uriVariables = [], array $context) {
        return new JsonResponse(['hello'], 200);
    }
}
```

Works just fine here.

Note that if you use `use_symfony_listeners=1` you'll hit `Could not resolve argument $data of "api_platform.action.placeholder::__invoke()` to work around that you need a provider: 

```php
<?php

namespace ApiPlatform\Tests\Fixtures\TestBundle\ApiResource\Issue2539;

use ApiPlatform\Metadata\Delete;
use ApiPlatform\Metadata\Operation;

#[Delete(
    provider: [self::class, 'provide'],
    uriTemplate: '/delete/{id}/with/{b}', uriVariables: ['id', 'b'], processor: [self::class, 'process']
)]
class DeleteWithProcessor
{
    public string $id;
    public string $b;

    // Note that this can return `\stdClass` or `null` 
    public static function provide(Operation $operation, array $uriVariables = [], array $context) {
        $a = new self();
        $a->id = $uriVariables['id'];
        $a->b = $uriVariables['b'];
        return $a;
    }

    public static function process(mixed $data, Operation $operation, array $uriVariables = [], array $context) {
        return null;
    }
}
```

**Comment by AliKHODR** [comment]
@soyuka Thanks

**Comment by aat-antoine** [comment]
My problem is about getting a batch delete sending data through body of DELETE and I have tried something like this but it seems we cant' use a state processor with delete operation. I read the message before in this conversation but it does not work.
(I'm using api platform 4.0.21 with `use_symfony_listeners: true` ) 

```
#[ApiResource(
    operations: [
        // This is a bulk delete but for unknown reason it is not working so I guess I need to use Post instead (not really cool) ?
        new Delete(
            uriTemplate: '/bulk/cars/unavailabilities/delete',
            input: DeleteCarUnavailabilityCollectionDto::class,
            output: DeleteCarUnavailabilityCollectionResponseDto::class,
            provider: [CarUnavailabilityCollectionDeleteProcessor::class, 'provide'],
            processor: [CarUnavailabilityCollectionDeleteProcessor::class, 'process'],
        ),
    ]
)]
```

Unfortunately I get this error

> ApiPlatform\Metadata\Metadata::getProcessor(): Return value must be of type callable|string|null, array returned
